name: Running code from GitHub action
'on': [push, pull_request]
jobs:
 my-job:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
  - uses: nanasess/setup-chromedriver@v2.2.2
  - uses: actions/upload-artifact@v4
    with:
      node-version: 18
  - run: mkdir -p path/to/artifact
  - run: echo hello > path/to/artifact/world.txt
  - uses: actions/upload-artifact@v4
    with:
      name: my-artifact
      path: path/to/artifact/world.txt    
  - run: npm install    
  - run: |
      export DISPLAY=:99
      chromedriver --url-base=/wd/hub &
      sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
  - run: npm ci
  - run: npx wdio
  
