name: Running code from GitHub action
'on': push
jobs:
 my-job:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: 18
  - run: npm ci
  - run: npm test
